### PR TITLE
Modified license to MIT

### PR DESCRIPTION
**Pull request by justin0022**
@jlongland, @andrew-gardener, I modified to license from GPL 3.0 to MIT, could you take a look?

Is the copyright holder `University of British Columbia`, or should it be more specific? `Learning Analytics` or `CTLT`?

### CODE REVIEW

**Comment by andrew-gardener** [comment]
https://github.com/ubc/iPeer/blob/master/LICENSE.txt#L3

https://github.com/ubc/loris-docker/blob/master/LICENSE#L3

https://github.com/ubc/examdb/blob/master/LICENSE#L1

Seems like we don't do it consistently so go with what you have (since learning analytics is jointly CTLT and UBC IT and I don't know if the LA team itself is a substantial enough entity to claim copyright on things long term)

**Comment by jlongland** [comment]
I don't see any issues, but I'm following up with management for confirmation. Please do not merge until I provide confirmation.

**Comment by justin0022** [comment]
Sounds good

**Comment by jlongland** [comment]
Change to MIT license approved by Senior Associate Director, Teaching and Learning Technologies. Copyright for all projects should be University of British Columbia.

**Pull request merged**
